aws_access_key = "${{ secrets.AWS_ACCESS_KEY }}" 
aws_secret_key = "${{ secrets.AWS_SECRET_KEY }}"
region         = "us-east-1"
db_name        = "lanchonete"
db_username    = "${{ secrets.DB_USERNAME }}"
db_password    = "${{ secrets.DB_PASSWORD }}"