name: Deploy RDS

on:
  pull_request:
    branches:
      - main   # Ou o nome da branch que você deseja usar para trigger
  workflow_dispatch:   # Permite disparar manualmente o workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout do repositório
    - name: Checkout code
      uses: actions/checkout@v3

    # Configurar o Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.10.1'  # Ajuste conforme a versão desejada

    # Configurar credenciais da AWS
    - name: Configure AWS credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      run: |
        mkdir -p ~/.aws
        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
        echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials

    # Inicializar o Terraform
    - name: Terraform Init
      run: terraform init

      # Validar o plano do Terraform
    - name: Terraform Plan
      run: terraform plan -out=tfplan -var="db_username=${{ secrets.DB_USERNAME }}" -var="db_password=${{ secrets.DB_PASSWORD }}"

    # Aplicar o plano do Terraform
    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan -var="db_username=${{ secrets.DB_USERNAME }}" -var="db_password=${{ secrets.DB_PASSWORD }}"